#ifndef DAT_TWS_H
#define DAT_TWS_H

#include "Tools.h"
#include <string>
#include <vector>
#include <iostream>
#include <cstring>
#include <ctime>

using namespace std;

namespace DatTws {

    extern csprng rng;
    extern gmp_randstate_t state_gmp;

    // ------------------------------
    // Data Structures
    // ------------------------------

    /**
     * @brief System public parameters.
     */
    typedef struct {
        mpz_class q;        ///< Order of the group.
        ECP X;              ///< Generator of group G1.
        ECP2 Y_tilde;       ///< Generator of group G2.
        FP12 hat_Z;         ///< Generator of group Gt, computed as e(X, Y_tilde).
    } DatParams;

    /**
     * @brief Opener's keys (Regulator/Tracer).
     */
    typedef struct {
        mpz_class rsk;      ///< Master View Secret Key (Opener's private key).
        ECP PK_R;           ///< Public View Key (in G1).
    } DatOpener;

    /**
     * @brief Issuer's keys.
     */
    typedef struct {
        mpz_class a, b;     ///< Signing private keys.
        ECP2 A_tilde;       ///< Verification Key component A (in G2).
        ECP2 B_tilde;       ///< Verification Key component B (in G2).
    } DatIssuer;

    /**
     * @brief Tag structure generated by the user and opener.
     */
    typedef struct {
        mpz_class T_exp;    ///< Expiration timestamp.
        ECP X_t;            ///< Ephemeral key in G1 (X^t).
        ECP2 Y_t_tilde;     ///< Ephemeral key in G2 (Y^t).
        ECP T_vk;           ///< Temporary Verification Key in G1.
        ECP2 A_tilde;       ///< Issuer PK part copy.
        ECP2 B_tilde;       ///< Issuer PK part copy.
    } DatTag;

    /**
     * @brief Witness structure generated by the issuer.
     */
    typedef struct {
        ECP sigma_prime;    ///< Unblinded partial signature (sigma').
    } DatWitness;

    /**
     * @brief User structure holding keys and collected credentials.
     */
    typedef struct {
        mpz_class usk;      ///< User Secret Key.
        ECP2 PK_U;          ///< User Public Key (in G2).
        ECP H;              ///< User's random base H.

        vector<DatTag> tags;            ///< Collection of generated tags.
        vector<DatWitness> witnesses;   ///< Collection of corresponding witnesses.
        vector<ECP> T_sk;               ///< Collection of derived temporary secret keys.
    } DatUser;

    /**
     * @brief Final aggregated signature structure.
     */
    typedef struct {
        ECP H_prime;        ///< Randomized Base H'.
        ECP sigma_prime;    ///< Randomized Witness Aggregation sigma'.
        FP12 R;             ///< Zero-Knowledge Commitment R.
        mpz_class s;        ///< Zero-Knowledge Response s.
        FP12 hat_Z_x;       ///< Randomized Generator Z^x.
        ECP sigma_x;        ///< Message Signature sigma_x.
        ECP2 PK_U_tilde_r;  ///< Randomized User Public Key.
    } DatSignature;

    // ------------------------------
    // Core Algorithms
    // ------------------------------

    /**
     * @brief Setup algorithm to generate system public parameters.
     * @return The generated public parameters structure.
     */
    DatParams Setup();

    /**
     * @brief Key Generation algorithm for all entities (Opener, Issuers, User).
     * @param pp System public parameters.
     * @param opener Output parameter for Opener's keys.
     * @param issuers Output parameter for the list of Issuers' keys.
     * @param n_issuers Number of issuers to generate.
     * @param user Output parameter for User's keys.
     */
    void KeyGen(DatParams pp, DatOpener &opener, vector<DatIssuer> &issuers, int n_issuers, DatUser &user) ;

    /**
     * @brief Tag Generation algorithm creates a temporary identity tag.
     * @param pp System public parameters.
     * @param issuer The target issuer for this tag.
     * @param user The user generating the tag.
     * @param opener The opener entity (for encryption of identity).
     * @return The generated DatTag structure.
     */
    DatTag TagGen(DatParams pp, DatIssuer issuer, DatUser user, DatOpener opener);

    /**
     * @brief Witness Generation algorithm (Issuance protocol).
     * The issuer generates a blinded signature (witness) on the user's tag.
     * The result is automatically pushed into the user's witness vector.
     * @param pp System public parameters.
     * @param issuer The issuer signing the tag.
     * @param user The user receiving the witness (updated in-place).
     * @param tag The tag to be signed.
     */
    void WitGen(DatParams pp, DatIssuer issuer, DatUser& user, DatTag tag, DatOpener opener);

    /**
     * @brief Signing algorithm to generate an aggregated signature on a message.
     * @param pp System public parameters.
     * @param user The user structure containing collected tags and witnesses.
     * @param msg The message to sign.
     * @return The generated DatSignature.
     */
    DatSignature Sign(DatParams pp, DatUser user, string msg);

    /**
     * @brief Verification algorithm to check the validity of the signature.
     * @param pp System public parameters.
     * @param sig The signature to verify.
     * @param tags The vector of tags corresponding to the signature.
     * @param msg The signed message.
     * @return True if the signature is valid; otherwise, false.
     */
    bool Verify(DatParams pp, DatSignature sig, vector<DatTag> tags, string msg);

    /**
     * @brief Partial Verification algorithm for cached/trusted credentials.
     * * If a specific tag has already been verified by the verifier, since only the
     * user corresponding to that tag possesses the associated witness, we can safely
     * skip the Zero-Knowledge Proof (ZK) verification. By directly checking the
     * validity of the message signature against these known tags, this algorithm
     * significantly reduces the computational overhead for subsequent authentications.
     * @param pp System public parameters.
     * @param sig The signature to verify.
     * @param tags The vector of tags corresponding to the signature.
     * @param msg The signed message.
     * @return True if the partial signature verification succeeds; otherwise, false.
     */
    bool parVerify(DatParams pp, DatSignature sig, vector<DatTag> tags, string msg);

    // ------------------------------
    // Helper / Hash Functions
    // ------------------------------

    /**
     * @brief Simulated pseudo-random function f used by Regulator to compute H_u.
     */
    mpz_class f_hash(mpz_class rsk, ECP2 PK_U);

    /**
     * @brief Hash function H1 used for generating T_vk.
     * @param Xt Ephemeral key in G1.
     * @param Yt Ephemeral key in G2.
     * @param pairing_res Result of pairing e(PK_R^t, PK_U).
     * @return Hash output as a large integer.
     */
    mpz_class H1(ECP Xt, ECP2 Yt, FP12 pairing_res);

    /**
     * @brief Hash function H2 used for the message signature challenge.
     * Computes h = H4(msg, Z_x, {T_vk}).
     * @param msg The message to sign.
     * @param hat_Z_x Randomized generator component (Z^x).
     * @param T_vks Vector of temporary verification keys.
     * @return Hash output as a large integer.
     */
    mpz_class H2(string msg, FP12 hat_Z_x, vector<ECP> T_vks);

    /**
     * @brief Hash function H3 used for the Zero-Knowledge Proof challenge.
     * Computes c = H3(K_agg, H', sigma', R).
     * @param K_agg Aggregated verification key.
     * @param H_prime Randomized base H'.
     * @param sigma_prime Randomized aggregated witness.
     * @param R Zero-Knowledge commitment.
     * @return Hash output as a large integer.
     */
    mpz_class H3(ECP2 K_agg, ECP H_prime, ECP sigma_prime, FP12 R);

    /**
     * @brief Hash function H_Tag used to compute the message representative m_i of a tag.
     * @param tag The tag structure.
     * @return Hash output as a large integer.
     */
    mpz_class H_Tag(const DatTag& tag);

    /**
     * @brief Batch verifies the Zero-Knowledge proofs for multiple aggregated signatures.
     * This ensures privacy and prevents forgery using a randomized small exponent test.
     * @param pp The public parameters of the DAT-TWS system.
     * @param sigs A vector of DatSignature objects containing the proofs.
     * @param all_tags A 2D vector where each element is a vector of DatTags corresponding to a user's signature.
     * @return True if all ZK proofs in the batch are valid, false otherwise.
     */
    bool batchVerifyZK(DatParams pp, vector<DatSignature> sigs, vector<vector<DatTag>> all_tags);

    /**
     * @brief Batch verifies the message signatures from multiple users concurrently.
     * It compresses multiple pairings into a single verification equation using random exponents.
     * @param pp The public parameters of the DAT-TWS system.
     * @param sigs A vector of DatSignature objects containing the message signatures.
     * @param all_tags A 2D vector where each element is a vector of DatTags corresponding to a user's signature.
     * @param msgs A vector of string messages signed by the respective users.
     * @return True if all message signatures in the batch are valid, false otherwise.
     */
    bool batchParVerify(DatParams pp, vector<DatSignature> sigs, vector<vector<DatTag>> all_tags, vector<string> msgs);

    /**
     * @brief An integrated interface to perform complete batch verification.
     * It internally executes both ZK proof batch verification and message signature batch verification.
     * @param pp The public parameters of the DAT-TWS system.
     * @param sigs A vector of DatSignature objects.
     * @param all_tags A 2D vector of DatTags.
     * @param msgs A vector of string messages.
     * @return True if the entire batch (ZK proofs + Signatures) is successfully verified, false otherwise.
     */
    bool batchVerifyAll(DatParams pp, vector<DatSignature> sigs, vector<vector<DatTag>> all_tags, vector<string> msgs);

} // namespace DatTws

#endif // DAT_TWS_H